// generatePdf.js
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const LOGO_BASE64 = require('./Base64');

function generatePdf(plan) {
  return new Promise((resolve, reject) => {
    try {
      const outputDir = path.join(__dirname, 'output');
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir);
      }

      const fileName = `RUNIQ_${plan.meta.distanceLabel}_Training_Plan.pdf`;
      const filePath = path.join(outputDir, fileName);

      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 50, right: 50 },
      });

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      /* =========================
         COLORS
      ========================= */
      const DARK = '#0B1320';
      const ACCENT = '#7ED6B2';
      const MUTED = '#6B7280';

      /* =========================
         COVER PAGE
      ========================= */

      // Logo
      const logoBuffer = Buffer.from(LOGO_BASE64, 'base64');
      doc.image(logoBuffer, {
        fit: [180, 80],
        align: 'center',
      });

      doc.moveDown(3);

      doc
        .fillColor(DARK)
        .fontSize(28)
        .text(`${plan.meta.distanceLabel} Training Plan`, {
          align: 'center',
        });

      doc.moveDown(1);

      doc
        .fillColor(MUTED)
        .fontSize(14)
        .text(`Duration: ${plan.meta.weeks} weeks`, { align: 'center' })
        .text(`Sessions per week: ${plan.meta.sessionsPerWeek}`, {
          align: 'center',
        })
        .text(`Goal time: ${plan.meta.goalTime}`, { align: 'center' });

      doc.moveDown(4);

      doc
        .fillColor(ACCENT)
        .fontSize(12)
        .text('Train smart. Race strong.', { align: 'center' });

      doc.addPage();

      /* =========================
         WEEK PAGES
      ========================= */

      plan.weeks.forEach((week) => {
        doc
          .fillColor(DARK)
          .fontSize(18)
          .text(`Week ${week.week}`, { continued: true });

        doc
          .fillColor(MUTED)
          .fontSize(12)
          .text(`  (${week.phase.toUpperCase()})`);

        doc.moveDown(0.5);

        doc
          .fillColor(ACCENT)
          .fontSize(12)
          .text(`Total distance: ${week.total_km} km`);

        doc.moveDown(1);

        week.sessions.forEach((session, index) => {
          const isRace = session.type === 'race';

          doc
            .fillColor(isRace ? '#C0392B' : DARK)
            .fontSize(13)
            .text(
              `${index + 1}. ${session.type.toUpperCase()} — ${
                session.distance_km
              } km`
            );

          doc
            .fillColor(MUTED)
            .fontSize(11)
            .text(session.description);

          doc.moveDown(0.8);
        });

        doc.addPage();
      });

      /* =========================
         FOOTER
      ========================= */

      doc
        .fillColor(MUTED)
        .fontSize(9)
        .text(
          'Generated by RUNIQ — Structured endurance training built for long-term progress.',
          {
            align: 'center',
          }
        );

      doc.end();

      stream.on('finish', () => {
        resolve({
          filePath,
          fileName,
        });
      });
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = generatePdf;
